set nocompatible

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" UI
syntax on

set number
set wildmenu
set cursorline
set colorcolumn=120
set laststatus=2

" Tabs
set noexpandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Backup and swap
set noswapfile
set nobackup
set nowritebackup

" Buffers
set hidden

" History
set history=100

" Plugins
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'L9'
Plugin 'Valloric/YouCompleteMe'
Plugin 'VundleVim/Vundle.vim'
Plugin 'a.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'b4winckler/vim-angry'
Plugin 'bkad/CamelCaseMotion'
Plugin 'easymotion/vim-easymotion'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'mileszs/ack.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'nvie/vim-flake8'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-abolish.git'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()

filetype plugin indent on

" Colour scheme
set background=dark
colorscheme solarized

" vim-better-whitespace
autocmd BufWritePre * StripWhitespace

" ack
if executable('rg')
    let g:ackprg = 'rg --vimgrep --no-heading'
endif

" vim-commentary
autocmd FileType cpp setlocal commentstring=//\ %s

" NERDtree
let NERDTreeIgnore=['\.class', '\.pyc$', '\~$']

" YouCompleteMe
let g:ycm_autoclose_preview_window_after_completion=1
let g:ycm_confirm_extra_conf=0
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
let g:ycm_show_diagnostics_ui=0

" VimAirline
let g:airline_powerline_fonts=1
let g:airline_theme='solarized'
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#fnamemod=':t'

" CamelCaseMotion
call camelcasemotion#CreateMotionMappings(',')

" commentary.vim
autocmd FileType cpp setlocal commentstring=//\ %s

" Python files
autocmd FileType python map <buffer> <leader>c :call Flake8()<CR>

" YAML files
autocmd FileType yaml setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

" Java files
autocmd FileType java setlocal expandtab

" Mappings
nnoremap <leader>d "_d
nnoremap <leader>x "_x

nnoremap <leader>w <C-w>
nnoremap <leader>q :q<CR>

nnoremap <leader>b :bp\|bd #<CR>

nnoremap Y y$

nnoremap <leader>c :History:<CR>
nnoremap <leader>f :Files<CR>
nnoremap <leader>t :BTags<CR>

nnoremap <leader>gs :Gst<CR>
nnoremap <leader>gp :Gpush<CR>
nnoremap <leader>gl :Gpull<CR>

nnoremap <leader>e :NERDTreeToggle<CR>
nnoremap <leader>r :NERDTreeFind<CR>

nnoremap <leader>s :Ack -w <C-r><C-w><CR>

nnoremap <C-j> :YcmCompleter GoTo<CR>

nnoremap <C-h> :A<CR>

nnoremap <C-n> :noh<CR>

" External .vimrc
set exrc
set secure
