export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(fabric git tmuxinator vi-mode virtualenv golang)

alias gre='git review $(git rev-parse --abbrev-ref HEAD)'

export GOPATH=$HOME/golang
export PATH=$HOME/bin:/usr/local/bin:$GOPATH/bin:/usr/local/go/bin:$PATH

source $ZSH/oh-my-zsh.sh

export ACKRC=".ackrc"
export EDITOR='vim'
export FZF_DEFAULT_COMMAND='ag --hidden -g ""'

DEFAULT_USER=$USER

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
