export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(brew docker git npm tmuxinator vi-mode yarn)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export EDITOR="vim"

export FZF_DEFAULT_COMMAND="rg --files --hidden"

DEFAULT_USER=$USER

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zshrc.user ] && source ~/.zshrc.user
